### ISSUE TITLE
AIS missing boat name

### ISSUE THREAD

**Issue by xpillons** [mak08/VRDashboard#20]
Boat name should be added in the trace

**Comment by whitehat42** [comment]
A new AIS trame with message type 5 must be send too with the same MMSI.

http://www.bosunsmate.org/ais/message5.php

**Comment by xpillons** [comment]
Yes and more complete from here https://gpsd.gitlab.io/gpsd/AIVDM.html#_type_5_static_and_voyage_related_data

**Comment by xpillons** [comment]
I'm working on it, I have something working now but I need to fix few bugs.

**Comment by whitehat42** [comment]
Oh perfect ! Thank you.

I could probably help you this weekend if needed.

**Comment by xpillons** [comment]
I've created a pull request #28 
Please @whitehat42 have a look. See the comments for limitations and known issues.

**Comment by whitehat42** [comment]
Hello,

I tested your pull request and it's working :) Thanks you very much !

I think you can replace all special char (' _ - ...) by a a space. I don't know why number is failing. Why do you use uppercase ? lowercase is ok.

@mak08 can you add this AIS version to the master branch ?

**Comment by mak08** [comment]
The ais branch is based on a patch from Jérémy Rubert. I'd like him to comment, but if he doesn't answer soon I'll merge this anyway.

**Comment by xpillons** [comment]
> Hello,
> 
> I tested your pull request and it's working :) Thanks you very much !
> 
> I think you can replace all special char (' _ - ...) by a a space. I don't know why number is failing. Why do you use uppercase ? lowercase is ok.
> 
> @mak08 can you add this AIS version to the master branch ?

Thanks for testing. I'm using uppercase because in the encoding table there are no lowercase chars.
