### ISSUE TITLE
Some options are double in fleet table

### ISSUE THREAD

**Issue by amoutiers** [mak08/VRDashboard#26]
Hello,

Some options are in double in the fleet table, which can cause : 
- false positive "Full Pack"
- cause Factor to be in red.

![Capture d’écran 2020-11-16 à 10 02 47](https://user-images.githubusercontent.com/2652014/99250783-86ba3180-280c-11eb-98c8-0aa5d62bca80.png)

I'll make a PR to fix that after work ;-)

Have a nice day

**Comment by mcmgj** [comment]
Hello, 



With the VRO3 version, I added a test (in my local version) to differentiate the "All Options" from the "Full Pack" by indicating FULL or ALL in the equipment box, the same should be done for the VRO4 version 



Have a good day ----- Mail original -----

De: "Antoine Moutiers" <notifications@github.com> 
À: "mak08/VRDashboard" <VRDashboard@noreply.github.com> 
Cc: "Subscribed" <subscribed@noreply.github.com> 
Envoyé: Lundi 16 Novembre 2020 13:07:54 
Objet: [mak08/VRDashboard] Some options are double (#26) 



Hello, 
Some options are in double in the fleet table, which can cause 👍 

    * false positive "Full Pack" 
    * cause Factor to be in red. 

Capture d’écran 2020-11-16 à 10 02 47
I'll make a PR to fix that after work ;-) 
Have a nice day

**Comment by amoutiers** [comment]
@mcmgj Done in the PR, if you can test in your local.

**Comment by amoutiers** [comment]
Thanks Mak08
