### ISSUE TITLE
NMEA INMWV: TWA or TWD?

### ISSUE THREAD

**Issue by mak08** [mak08/VRDashboard#31]
NMEA users, 
can you please comment how the INMWV message should look like?
I changed from TWA to TWD based on a comment by itournell [here](https://chrome.google.com/webstore/detail/vr-dashboard/amknkhejaogpekncjekiaolgldbejjan?hl=de&authuser=0).
Not everyone seems to agree this was good change.

**Comment by xpillons** [comment]
yes agree that this change broke what is reported in both qtVLM and Adrena. I will have a look at the message structure.

**Comment by GeGaX** [comment]
Hi Michael ;)
You changed TWA to TWD and the routers are going crazy.
Is there a specific reason for this change?

Edit: I just read the comment on the Chrome Web Store, I will dive back into the NMEA code, but there is an error in its understanding.

**Comment by DurnezJurgen** [comment]
Hi,

I thinks It's because you sent before TWA it's an angle with MWV. (Wind Speed and Angle)
Now you send the TWD but still with MWV you should use MWD. (Wind Direction & Speed)
please double check I'm not a specialist ;-)

Hope it's helping a little.
Regards

source: https://confluence.qps.nl/dm/nmea-miscellaneous-rot-mwd-mwv-23-25821237.html

**Comment by GeGaX** [comment]
$MWV = TWA & TWS (or AWA & AWS if HDG & SPD are transmited)
$MWD = TWD & TWS

**Comment by SynCinatti** [comment]
Hello;

I'm kind of new to all this boat-specific stuff, so i just will suggest to revert back as of previous TWA definition until current races are closed (Vendee Globe actually) and further offline testing succeeds ; it indeed heavily interfers with client softwares, which could make a lot of users unhappy.

Regards,

EDIT : I forgot to thank you for this great job in the whole ! Two weeks with the dashboard and can't live without it anymore when running VR :D

**Comment by tetramonium** [comment]
Same problem for me with qtvlm
Thank you

**Comment by mak08** [comment]
I only have second hand info but all the docs I found speak about wind angle and wind direction. MWV carries wind angle, not direction. I'll revert the previous change.

**Comment by mgold99** [comment]
No sense having secondhand info: [Here's a version](http://www.plaisance-pratique.com/IMG/pdf/NMEA0183-2.pdf) of the NMEA0183 spec I found (note that it's not the latest). 
pp58-59 describe MWD as wind speed and direction (as it blows on the earth's surface - TWD and TWS); and MWV as speed and angle, but can be either "t"heoretical (eg to a vessel at rest - TWA and TWS) or "r"elative (to moving vessel - AWA and AWS). So maybe it's a matter of sending "R" and AWA and AWS. But worth it to test first! :) 

Agree with reverting, no sense having a breaking change mid-race. Dashboard is awesome!!

**Comment by jptrol** [comment]
Sorry, you are all right . It was all my fault.  I remembered a few sentences were declared obsolete in 2010 and thought the MWD sentence was one of them, but of course no.  I asked Micheal to correct a mistake that was not one :
The MWD sentence gives the TWD and the TWS refered to the North 
The MWV  T type sentence gives the TWA  refered to the bow of the ship and the TWS  (I never used this type)
The MWV  R type sentence gives the AWA  refered to the bow of the ship and the AWS
All this would be more obvious if the specs did not cost a fortune !
Best regards

Extract from 
NMEA 0183
Standard For Interfacing
Marine Electronic Devices
Version 3.01
January 1, 2002

MWV - Wind Speed and Angle
When the reference field is set to R (Relative), data is provided giving the wind angle in relation to the
vessel's bow/centerline and the wind speed, both relative to the (moving) vessel. Also called apparent
wind, this is the wind speed as felt when standing on the (moving) ship.
When the reference field is set to T (Theoretical, calculated actual wind), data is provided giving the wind
angle in relation to the vessel's bow/centerline and the wind speed as if the vessel was stationary. On a
moving ship these data can be calculated by combining the measured relative wind with the vessel's own
speed.
Example 1: If the vessel is heading west at 7 knots and the wind is from the east at 10 knots the relative
wind is 3 knots at 180 degrees. In this same example the theoretical wind is 10 knots at 180 degrees (if the
boat suddenly stops the wind will be at the full 10 knots and come from the stern of the vessel 180 degrees
from the bow).
Example 2: If the vessel is heading west at 5 knots and the wind is from the southeast at 7.07 knots the
relative wind is 5 knots at 270 degrees. In this same example the theoretical wind is 7.07 knots at 225
degrees (if the boat suddenly stops the wind will be at the full 7.07 knots and come from the port-quarter
of the vessel 225 degrees from the bow).
$--MWV,x.x,a,x.x,a,A*hh<CR><LF>
Status, A = Data Valid, V = Data invalid
Wind speed units, K/M/N/S
Wind speed
Reference, R = Relative
T = Theoretical
Wind angle, 0 to 359 degrees

**Comment by SynCinatti** [comment]
The dashboard auto-updated 3 minutes ago and the right twa is back .

Thank you !

**Comment by mak08** [comment]
Fix is merged.

**Comment by jptrol** [comment]
Thank you , Michael.

**Comment by DurnezJurgen** [comment]
Thkx a lot...

Jurgen

Envoyé de mon iPhone
