### ISSUE TITLE
Trace on Map

### ISSUE THREAD

**Issue by DurnezJurgen** [mak08/VRDashboard#32]
Hi,

Thanks a lot for your job.

Just a little question, nothing urgent, for the moment on the map I don't see correctly the trace, too many black boxes (see picture). 
Do am I alone to have this? 
Any work around? Like I told it's just a detail...

Thanks, have a nice day.
Jürgen

![vrdashboard](https://user-images.githubusercontent.com/22387672/101606921-3e092900-3a04-11eb-83bb-7a95240ed69a.JPG)

**Comment by DurnezJurgen** [comment]
ok sorry my bad, just an option to remove thks to Syn...

**Comment by mak08** [comment]
The dots have tooltips with boat speed and boat actions but creating such a large number of map markers wasn't a very good idea. It's best to keep it turned off. Closing the issue as you found out how.
