### ISSUE TITLE
Autoupdate fleet boats positions

### ISSUE THREAD

**Issue by SynCinatti** [mak08/VRDashboard#33]
Hello,

Thanks again for this great job :) 

I was wondering whether it would be anyhow possible to collect current other boats positions when updating the game? At this time we have to manually click on other boats in the game to update their positions on the chart in the dashboard.

Regards,

**Comment by mak08** [comment]
VRDashboard is completely passive, meaning it can read the messages exchanged between the browser and the VR server, but it can't trigger messages itself. When you press the refresh button in the game, the whole fleet should be updated. VRDashboard may miss the fleet update sometimes if the server takes too long to respond (not 100% sure) but normally it should happen.

As a VR VIP member you get automatic refresh (so I am told), but I'm not promoting VIP membership ;-)

**Comment by SynCinatti** [comment]
Actually only the clicked boat will refresh.. but no matter. we were discussing this point with Jurgen and came to the conclusion that indeed the fleet positions would not be pushed but pulled.
So.. let's go, issue to be closed ;-)

Thank you !

**Comment by SynCinatti** [comment]
Oh sorry.. actually i wanted to talk about the fleet boats rank, not their positions.. guess the answer will gonna be the same ;) If not let me know !

**Comment by mak08** [comment]
Yes, answer is the same. To summarize:
- When you click on a boat the VR game client only fetches info on this boat, including the rank.
- The fleet is updated when you click the refresh button that appears every 10min. This includes boat speed, position, heading and TWA but NOT rank information.

**Comment by SynCinatti** [comment]
That's how it happens indeed. Maybe could it be tricked and masse-updated by checking the leaderboards ? I'll give it a look next time i reload the dash.

Issue to be closed, again.

Thanks for replying !
