### ISSUE TITLE
Some routing app can't use MVW True Wind Angle

### ISSUE THREAD

**Issue by amoutiers** [mak08/VRDashboard#39]
Hello,

Some routing app (like Weather4D on IOS) can't use MVW in True wind mode.
On a boat we want to calculate TWA/TWS as we already know AWA/AWD that are reported by electronic.

I add :
- VWR sentence that is explicitly design for AWA/AWS
- VHW sentence to send the heading and speed.
- MWV is keept for routing app that support True wind

So the app can know calculate TWA/TWS by using the two added sentences and the good news is that's the same as reported by the dashboard.

Have a nice day

**Comment by mak08** [comment]
This is getting complicated :-)
I merged your pull request into the NMEAdev branch. Does this fix this issue?

**Comment by amoutiers** [comment]
Yes it was fixed.
I had another sentense in my dev version to get Laylines support. I'll make another PR soon.
